# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.models.empty import Empty  # noqa: E501
from hiarc.rest import ApiException


class TestEmpty(unittest.TestCase):
    """Empty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmpty(self):
        """Test Empty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hiarc.models.empty.Empty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
