# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.api.legal_hold_api import LegalHoldApi  # noqa: E501
from hiarc.rest import ApiException


class TestLegalHoldApi(unittest.TestCase):
    """LegalHoldApi unit test stubs"""

    def setUp(self):
        self.api = LegalHoldApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_legal_hold(self):
        """Test case for create_legal_hold

        Create a Legal Hold  # noqa: E501
        """
        pass

    def test_get_legal_hold(self):
        """Test case for get_legal_hold

        Get a Legal Hold's Info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
