# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.models.list_of_retention_policies import ListOfRetentionPolicies  # noqa: E501
from hiarc.rest import ApiException


class TestListOfRetentionPolicies(unittest.TestCase):
    """ListOfRetentionPolicies unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListOfRetentionPolicies(self):
        """Test ListOfRetentionPolicies"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hiarc.models.list_of_retention_policies.ListOfRetentionPolicies()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
