# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.api.collection_api import CollectionApi  # noqa: E501
from hiarc.rest import ApiException


class TestCollectionApi(unittest.TestCase):
    """CollectionApi unit test stubs"""

    def setUp(self):
        self.api = CollectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_child_to_collection(self):
        """Test case for add_child_to_collection

        Add a child item to a Collection  # noqa: E501
        """
        pass

    def test_add_file_to_collection(self):
        """Test case for add_file_to_collection

        Add a File to a Collection  # noqa: E501
        """
        pass

    def test_add_group_to_collection(self):
        """Test case for add_group_to_collection

        Add a Group to a Collection  # noqa: E501
        """
        pass

    def test_add_user_to_collection(self):
        """Test case for add_user_to_collection

        Add a User to a Collection  # noqa: E501
        """
        pass

    def test_create_collection(self):
        """Test case for create_collection

        Create a Collection  # noqa: E501
        """
        pass

    def test_delete_collection(self):
        """Test case for delete_collection

        Delete a Collection  # noqa: E501
        """
        pass

    def test_find_collection(self):
        """Test case for find_collection

        Find a Collection  # noqa: E501
        """
        pass

    def test_get_all_collections(self):
        """Test case for get_all_collections

        Get all Collections  # noqa: E501
        """
        pass

    def test_get_collection(self):
        """Test case for get_collection

        Get a Collection's Info  # noqa: E501
        """
        pass

    def test_get_collection_children(self):
        """Test case for get_collection_children

        Get a Collection's child Collections  # noqa: E501
        """
        pass

    def test_get_collection_files(self):
        """Test case for get_collection_files

        Get a Collection's Files  # noqa: E501
        """
        pass

    def test_get_collection_items(self):
        """Test case for get_collection_items

        Get a Collection's child items, including Collections and Files  # noqa: E501
        """
        pass

    def test_remove_file_from_collection(self):
        """Test case for remove_file_from_collection

        Remove a File from a Collection  # noqa: E501
        """
        pass

    def test_update_collection(self):
        """Test case for update_collection

        Update a Collection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
