# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.models.create_classification_request import CreateClassificationRequest  # noqa: E501
from hiarc.rest import ApiException


class TestCreateClassificationRequest(unittest.TestCase):
    """CreateClassificationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateClassificationRequest(self):
        """Test CreateClassificationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hiarc.models.create_classification_request.CreateClassificationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
