# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.api.group_api import GroupApi  # noqa: E501
from hiarc.rest import ApiException


class TestGroupApi(unittest.TestCase):
    """GroupApi unit test stubs"""

    def setUp(self):
        self.api = GroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user_to_group(self):
        """Test case for add_user_to_group

        Add a User to a Group  # noqa: E501
        """
        pass

    def test_create_group(self):
        """Test case for create_group

        Create a Group  # noqa: E501
        """
        pass

    def test_delete_group(self):
        """Test case for delete_group

        Delete a Group  # noqa: E501
        """
        pass

    def test_find_group(self):
        """Test case for find_group

        Find a Group  # noqa: E501
        """
        pass

    def test_get_all_groups(self):
        """Test case for get_all_groups

        Get all Groups  # noqa: E501
        """
        pass

    def test_get_group(self):
        """Test case for get_group

        Get a Group's Info  # noqa: E501
        """
        pass

    def test_get_groups_for_current_user(self):
        """Test case for get_groups_for_current_user

        Get the Groups for the current User  # noqa: E501
        """
        pass

    def test_update_group(self):
        """Test case for update_group

        Update a Group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
