# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.models.add_file_to_collection_request import AddFileToCollectionRequest  # noqa: E501
from hiarc.rest import ApiException


class TestAddFileToCollectionRequest(unittest.TestCase):
    """AddFileToCollectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddFileToCollectionRequest(self):
        """Test AddFileToCollectionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hiarc.models.add_file_to_collection_request.AddFileToCollectionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
