# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.api.classification_api import ClassificationApi  # noqa: E501
from hiarc.rest import ApiException


class TestClassificationApi(unittest.TestCase):
    """ClassificationApi unit test stubs"""

    def setUp(self):
        self.api = ClassificationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_classification(self):
        """Test case for create_classification

        Create a Classification  # noqa: E501
        """
        pass

    def test_delete_classification(self):
        """Test case for delete_classification

        Delete a Classification  # noqa: E501
        """
        pass

    def test_find_classification(self):
        """Test case for find_classification

        Find a Classification  # noqa: E501
        """
        pass

    def test_get_all_classifications(self):
        """Test case for get_all_classifications

        Get all Classifications  # noqa: E501
        """
        pass

    def test_get_classification(self):
        """Test case for get_classification

        Get a Classification's Info  # noqa: E501
        """
        pass

    def test_update_classification(self):
        """Test case for update_classification

        Update a Classification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
