# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.models.find_retention_policies_request import FindRetentionPoliciesRequest  # noqa: E501
from hiarc.rest import ApiException


class TestFindRetentionPoliciesRequest(unittest.TestCase):
    """FindRetentionPoliciesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFindRetentionPoliciesRequest(self):
        """Test FindRetentionPoliciesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hiarc.models.find_retention_policies_request.FindRetentionPoliciesRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
