# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.api.user_api import UserApi  # noqa: E501
from hiarc.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        Create a User  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete a User  # noqa: E501
        """
        pass

    def test_find_user(self):
        """Test case for find_user

        Find a User  # noqa: E501
        """
        pass

    def test_get_all_users(self):
        """Test case for get_all_users

        Get all Users  # noqa: E501
        """
        pass

    def test_get_current_user(self):
        """Test case for get_current_user

        Get the current User  # noqa: E501
        """
        pass

    def test_get_groups_for_current_user(self):
        """Test case for get_groups_for_current_user

        Get the Groups for the current User  # noqa: E501
        """
        pass

    def test_get_groups_for_user(self):
        """Test case for get_groups_for_user

        Get Groups for a User  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get a User  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update a User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
