# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.api.admin_api import AdminApi  # noqa: E501
from hiarc.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_init_db(self):
        """Test case for init_db

        Init the Hiarc database  # noqa: E501
        """
        pass

    def test_reset_db(self):
        """Test case for reset_db

        Reset the Hiarc database  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
