# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.api.file_api import FileApi  # noqa: E501
from hiarc.rest import ApiException


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self):
        self.api = FileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_classification_to_file(self):
        """Test case for add_classification_to_file

        Add a Classification to a File  # noqa: E501
        """
        pass

    def test_add_group_to_file(self):
        """Test case for add_group_to_file

        Give a group access to a File  # noqa: E501
        """
        pass

    def test_add_retention_policy_to_file(self):
        """Test case for add_retention_policy_to_file

        Add a Retention Policy to a File  # noqa: E501
        """
        pass

    def test_add_user_to_file(self):
        """Test case for add_user_to_file

        Give a user access to a File  # noqa: E501
        """
        pass

    def test_add_version(self):
        """Test case for add_version

        Add a new File Version  # noqa: E501
        """
        pass

    def test_attach_to_exisiting_file(self):
        """Test case for attach_to_exisiting_file

        Attach to an existing File  # noqa: E501
        """
        pass

    def test_copy_file(self):
        """Test case for copy_file

        Copy a File  # noqa: E501
        """
        pass

    def test_create_direct_upload_url(self):
        """Test case for create_direct_upload_url

        Create a direct upload url to a storage service  # noqa: E501
        """
        pass

    def test_create_file(self):
        """Test case for create_file

        Create a File  # noqa: E501
        """
        pass

    def test_delete_file(self):
        """Test case for delete_file

        Delete a File  # noqa: E501
        """
        pass

    def test_download_file(self):
        """Test case for download_file

        Download a File  # noqa: E501
        """
        pass

    def test_get_collections_for_file(self):
        """Test case for get_collections_for_file

        Get a list of Collections for a File  # noqa: E501
        """
        pass

    def test_get_direct_download_url(self):
        """Test case for get_direct_download_url

        Get a direct download URL to a File  # noqa: E501
        """
        pass

    def test_get_file(self):
        """Test case for get_file

        Get a File's Info  # noqa: E501
        """
        pass

    def test_get_retention_policies(self):
        """Test case for get_retention_policies

        Get a list of Retention Policies on a File  # noqa: E501
        """
        pass

    def test_get_versions(self):
        """Test case for get_versions

        Get a list of File Versions  # noqa: E501
        """
        pass

    def test_update_file(self):
        """Test case for update_file

        Update a File  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
