# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.api.retention_policy_api import RetentionPolicyApi  # noqa: E501
from hiarc.rest import ApiException


class TestRetentionPolicyApi(unittest.TestCase):
    """RetentionPolicyApi unit test stubs"""

    def setUp(self):
        self.api = RetentionPolicyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_retention_policy(self):
        """Test case for create_retention_policy

        Create a Retention Policy  # noqa: E501
        """
        pass

    def test_find_retention_policies(self):
        """Test case for find_retention_policies

        Find a Retention Policy  # noqa: E501
        """
        pass

    def test_get_all_retention_policies(self):
        """Test case for get_all_retention_policies

        Get all Retention Policies  # noqa: E501
        """
        pass

    def test_get_retention_policy(self):
        """Test case for get_retention_policy

        Get a Retention Policy's Info  # noqa: E501
        """
        pass

    def test_update_retention_policy(self):
        """Test case for update_retention_policy

        Update a Retention Policy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
