# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hiarc
from hiarc.models.add_group_to_file_request import AddGroupToFileRequest  # noqa: E501
from hiarc.rest import ApiException


class TestAddGroupToFileRequest(unittest.TestCase):
    """AddGroupToFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddGroupToFileRequest(self):
        """Test AddGroupToFileRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hiarc.models.add_group_to_file_request.AddGroupToFileRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
