# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AddClassificationToFileRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'classification_key': 'str'
    }

    attribute_map = {
        'classification_key': 'classificationKey'
    }

    def __init__(self, classification_key=None):  # noqa: E501
        """AddClassificationToFileRequest - a model defined in Swagger"""  # noqa: E501
        self._classification_key = None
        self.discriminator = None
        if classification_key is not None:
            self.classification_key = classification_key

    @property
    def classification_key(self):
        """Gets the classification_key of this AddClassificationToFileRequest.  # noqa: E501


        :return: The classification_key of this AddClassificationToFileRequest.  # noqa: E501
        :rtype: str
        """
        return self._classification_key

    @classification_key.setter
    def classification_key(self, classification_key):
        """Sets the classification_key of this AddClassificationToFileRequest.


        :param classification_key: The classification_key of this AddClassificationToFileRequest.  # noqa: E501
        :type: str
        """

        self._classification_key = classification_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddClassificationToFileRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddClassificationToFileRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
