# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from hiarc.models.create_or_update_entity_request import CreateOrUpdateEntityRequest  # noqa: F401,E501

class CreateRetentionPolicyRequest(CreateOrUpdateEntityRequest):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'seconds': 'int'
    }
    if hasattr(CreateOrUpdateEntityRequest, "swagger_types"):
        swagger_types.update(CreateOrUpdateEntityRequest.swagger_types)

    attribute_map = {
        'seconds': 'seconds'
    }
    if hasattr(CreateOrUpdateEntityRequest, "attribute_map"):
        attribute_map.update(CreateOrUpdateEntityRequest.attribute_map)

    def __init__(self, seconds=None, *args, **kwargs):  # noqa: E501
        """CreateRetentionPolicyRequest - a model defined in Swagger"""  # noqa: E501
        self._seconds = None
        self.discriminator = None
        if seconds is not None:
            self.seconds = seconds
        CreateOrUpdateEntityRequest.__init__(self, *args, **kwargs)

    @property
    def seconds(self):
        """Gets the seconds of this CreateRetentionPolicyRequest.  # noqa: E501


        :return: The seconds of this CreateRetentionPolicyRequest.  # noqa: E501
        :rtype: int
        """
        return self._seconds

    @seconds.setter
    def seconds(self, seconds):
        """Sets the seconds of this CreateRetentionPolicyRequest.


        :param seconds: The seconds of this CreateRetentionPolicyRequest.  # noqa: E501
        :type: int
        """

        self._seconds = seconds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateRetentionPolicyRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateRetentionPolicyRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
