# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateUserTokenRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'expiration_minues': 'float'
    }

    attribute_map = {
        'key': 'key',
        'expiration_minues': 'expirationMinues'
    }

    def __init__(self, key=None, expiration_minues=None):  # noqa: E501
        """CreateUserTokenRequest - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._expiration_minues = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if expiration_minues is not None:
            self.expiration_minues = expiration_minues

    @property
    def key(self):
        """Gets the key of this CreateUserTokenRequest.  # noqa: E501


        :return: The key of this CreateUserTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this CreateUserTokenRequest.


        :param key: The key of this CreateUserTokenRequest.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def expiration_minues(self):
        """Gets the expiration_minues of this CreateUserTokenRequest.  # noqa: E501


        :return: The expiration_minues of this CreateUserTokenRequest.  # noqa: E501
        :rtype: float
        """
        return self._expiration_minues

    @expiration_minues.setter
    def expiration_minues(self, expiration_minues):
        """Sets the expiration_minues of this CreateUserTokenRequest.


        :param expiration_minues: The expiration_minues of this CreateUserTokenRequest.  # noqa: E501
        :type: float
        """

        self._expiration_minues = expiration_minues

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateUserTokenRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateUserTokenRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
