# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FileDirectDownload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'direct_download_url': 'str',
        'expires_at': 'datetime'
    }

    attribute_map = {
        'key': 'key',
        'direct_download_url': 'directDownloadUrl',
        'expires_at': 'expiresAt'
    }

    def __init__(self, key=None, direct_download_url=None, expires_at=None):  # noqa: E501
        """FileDirectDownload - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._direct_download_url = None
        self._expires_at = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if direct_download_url is not None:
            self.direct_download_url = direct_download_url
        if expires_at is not None:
            self.expires_at = expires_at

    @property
    def key(self):
        """Gets the key of this FileDirectDownload.  # noqa: E501


        :return: The key of this FileDirectDownload.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this FileDirectDownload.


        :param key: The key of this FileDirectDownload.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def direct_download_url(self):
        """Gets the direct_download_url of this FileDirectDownload.  # noqa: E501


        :return: The direct_download_url of this FileDirectDownload.  # noqa: E501
        :rtype: str
        """
        return self._direct_download_url

    @direct_download_url.setter
    def direct_download_url(self, direct_download_url):
        """Sets the direct_download_url of this FileDirectDownload.


        :param direct_download_url: The direct_download_url of this FileDirectDownload.  # noqa: E501
        :type: str
        """

        self._direct_download_url = direct_download_url

    @property
    def expires_at(self):
        """Gets the expires_at of this FileDirectDownload.  # noqa: E501


        :return: The expires_at of this FileDirectDownload.  # noqa: E501
        :rtype: datetime
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at):
        """Sets the expires_at of this FileDirectDownload.


        :param expires_at: The expires_at of this FileDirectDownload.  # noqa: E501
        :type: datetime
        """

        self._expires_at = expires_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FileDirectDownload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileDirectDownload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
