# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from hiarc.models.entity import Entity  # noqa: F401,E501

class File(Entity):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version_count': 'float'
    }
    if hasattr(Entity, "swagger_types"):
        swagger_types.update(Entity.swagger_types)

    attribute_map = {
        'version_count': 'versionCount'
    }
    if hasattr(Entity, "attribute_map"):
        attribute_map.update(Entity.attribute_map)

    def __init__(self, version_count=None, *args, **kwargs):  # noqa: E501
        """File - a model defined in Swagger"""  # noqa: E501
        self._version_count = None
        self.discriminator = None
        if version_count is not None:
            self.version_count = version_count
        Entity.__init__(self, *args, **kwargs)

    @property
    def version_count(self):
        """Gets the version_count of this File.  # noqa: E501


        :return: The version_count of this File.  # noqa: E501
        :rtype: float
        """
        return self._version_count

    @version_count.setter
    def version_count(self, version_count):
        """Sets the version_count of this File.


        :param version_count: The version_count of this File.  # noqa: E501
        :type: float
        """

        self._version_count = version_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(File, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, File):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
