# coding: utf-8

"""
    Hiarc API

    Welcome to the Hiarc API documentation.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RetentionPolicyApplication(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'retention_policy': 'RetentionPolicy',
        'applied_at': 'datetime',
        'expires_at': 'datetime'
    }

    attribute_map = {
        'retention_policy': 'retentionPolicy',
        'applied_at': 'appliedAt',
        'expires_at': 'expiresAt'
    }

    def __init__(self, retention_policy=None, applied_at=None, expires_at=None):  # noqa: E501
        """RetentionPolicyApplication - a model defined in Swagger"""  # noqa: E501
        self._retention_policy = None
        self._applied_at = None
        self._expires_at = None
        self.discriminator = None
        if retention_policy is not None:
            self.retention_policy = retention_policy
        if applied_at is not None:
            self.applied_at = applied_at
        if expires_at is not None:
            self.expires_at = expires_at

    @property
    def retention_policy(self):
        """Gets the retention_policy of this RetentionPolicyApplication.  # noqa: E501


        :return: The retention_policy of this RetentionPolicyApplication.  # noqa: E501
        :rtype: RetentionPolicy
        """
        return self._retention_policy

    @retention_policy.setter
    def retention_policy(self, retention_policy):
        """Sets the retention_policy of this RetentionPolicyApplication.


        :param retention_policy: The retention_policy of this RetentionPolicyApplication.  # noqa: E501
        :type: RetentionPolicy
        """

        self._retention_policy = retention_policy

    @property
    def applied_at(self):
        """Gets the applied_at of this RetentionPolicyApplication.  # noqa: E501


        :return: The applied_at of this RetentionPolicyApplication.  # noqa: E501
        :rtype: datetime
        """
        return self._applied_at

    @applied_at.setter
    def applied_at(self, applied_at):
        """Sets the applied_at of this RetentionPolicyApplication.


        :param applied_at: The applied_at of this RetentionPolicyApplication.  # noqa: E501
        :type: datetime
        """

        self._applied_at = applied_at

    @property
    def expires_at(self):
        """Gets the expires_at of this RetentionPolicyApplication.  # noqa: E501


        :return: The expires_at of this RetentionPolicyApplication.  # noqa: E501
        :rtype: datetime
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at):
        """Sets the expires_at of this RetentionPolicyApplication.


        :param expires_at: The expires_at of this RetentionPolicyApplication.  # noqa: E501
        :type: datetime
        """

        self._expires_at = expires_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RetentionPolicyApplication, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RetentionPolicyApplication):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
